create table KEYS (
    ID VARCHAR(50) PRIMARY KEY,
    KEY_NAME VARCHAR(50),
    KEY_VALUE VARCHAR(50)
);


create table PARAMETERS(
    PARAM_KEY VARCHAR(50) PRIMARY KEY,
    PARAM_VALUE VARCHAR(50)
)

